export const primeiroParagrafo = "> Meu nome é **Matheus Carvalho**, tenho 27 anos e sou graduando em Sistemas de Informação na **[Universidade Federal do Oeste do Pará - Campus Oriximiná](http://www.ufopa.edu.br/oriximina/)**. Moro em Santarém-Pará, mas faço meu curso de graduação na cidade de Oriximiná, uma pequena cidade do interior do Pará, mas em tamanho territorial, é o 4º maior do Brasil!! Atualmente trabalho como Desenvolvedor Backend, mas peguei amor pelo Frontend, e ainda, sou apaixonado por Data Science, área que futuramente pretendo trabalhar, mas que ja tive um gostinho através de um estágio na Equatorial Energia, onde participei no desenvolvimento de um algoritmo de predição a longo prazo usando Redes Bayesianas Dinamicas. O amor por cada uma dessas áreas veio através de bolsas de pesquisa na Universidade que graduo, e após as bolsas, continuei os estudos dentro de cada área e, por conta dessas oportunidades, consegui meu primeiro emprego de forma remota em uma empresa do Rio de Janeiro, a **[ED Company](https://ed.dev.br/)**. Foi incrível.";

export const segundoParagrafo = `Em 2019, fiz um intercambio na **[Chalmers University of Technology](https://www.chalmers.se/en/Pages/default.aspx)**, localizada em Gotemburgo, Suécia, através de uma bolsa disponibilizada pelo Programa de Mobilidade Interna (PMAI) da UFOPA. Lá tive uma pequena experiencia como pesquisador na área de Redes de Computadores, e vi o trabalho de grandes doutores pesquisadores na área de Redes Ópticas. Foi uma experiencia incrível, tanto profissional quanto pessoalmente! Conhecer pela primeira vez um lugar aém do Brasil, ainda mais saindo de uma cidade no interior do estado do Pará, foi realmente algo grande para mim.
`;

export const terceiroParagrafo = `As experiencias que acumulei até hoje dentro da Universidade e no Trabalho atual ainda são básica para intermediária, participando de projetos de pesquisas e projetos reais no mercado de trabalho como Desenvolvedor Backend Junior, porém sou capaz de construir: 

* API’s usando **[C#](https://learn.microsoft.com/pt-br/dotnet/csharp/)** com o framework **[.NET Core](https://learn.microsoft.com/pt-br/dotnet/core/introduction)** com **[Entity Framework Core](https://learn.microsoft.com/pt-br/ef/core/)** e usando **[Python](https://www.python.org/about/gettingstarted/)** com os frameworks **[Flask](https://flask.palletsprojects.com/en/2.2.x/)** e **[Fast API](https://fastapi.tiangolo.com/)**, além de de consumir essas API's REST. 

* Aplicações webs básicas e responsivas com a biblioteca **[React](https://pt-br.reactjs.org/tutorial/tutorial.html)** (ferramenta usada para construir este portfólio), e um pouquinho de conhecimento em **[Angular](https://angular.io/cli)**. 

* Aplicações mobile mais simples usando o framework **[Flutter](https://docs.flutter.dev/)**, uma ferramenta que peguei paixão muito rápido. 

* Tenho conhecimento sobre Metodologias Ágeis, como Scrum e Kanban, que são frameworks que vivencio diariamente, e além, claro, de conhecer seus conceitos. 

* E por último (Não menos importante), tenho conhecimento básico sobre o uso do **[KDD (Knowledge-Discovery in Databases)](https://www.devmedia.com.br/descoberta-de-conhecimento-utilizando-o-processo-kdd/38709)** utilizando a linguagem Python, e ainda, conhecimento básico em bancos de dados relacionais **([MySQL](https://www.alura.com.br/artigos/o-que-e-sql))**, e não relacionais **([MongoDB](https://www.mongodb.com/cloud/atlas/lp/try4?utm_source=google&utm_campaign=search_gs_pl_evergreen_atlas_core_prosp-brand_gic-null_amers-br_ps-all_desktop_eng_lead&utm_term=mongodb&utm_medium=cpc_paid_search&utm_ad=e&utm_ad_campaign_id=12212624308&adgroup=115749706023&gclid=Cj0KCQiA45qdBhD-ARIsAOHbVdFyqnk1jeifost6kTRV5zYKHJzP_VO6wt28j_wAnId1sOSzDxrj-KEaAh8EEALw_wcB))**. Ainda, consigo construir modelos básicos de **[Machine Learning](https://www.ibm.com/br-pt/cloud/learn/machine-learning)**, mas tenho muito a aprender ainda!
`;
